### ISSUE TITLE
Send SIGTERM after SIGINT

### ISSUE THREAD

**Issue by miluChen** [coleifer/huey#452]
Hi again!!!

Usually, when we want to kill a process, we'll first try to gracefully kill it. If it refuses to die, we may send another signal to force it to die.

Currently in `huey`, if we send a `SIGINT` to consumer, it'll set the stop flag and try to join the workers. If the workers refuse to die, the consumer has no choice but to wait. If we send another `SIGTERM` to consumer, it won't work because the corresponding signal handler only sets some variables. There doesn't seem to be a way to tell the consumer to not wait anymore and the second SIGTERM signal may be meaningless.

I think it'll be useful if `huey` provides the option that users can first try to gracefully kill the consumer, and also ungracefully kill the consumer if it won't die.

**Comment by coleifer** [comment]
> if it won't die.

What does that mean, though? Huey supports graceful shutdown, which will ensure that all tasks that are currently being worked on will finish (one way or the other). Alternatively, you can sigterm and stop everything regardless.

If you want a graceful shutdown but get impatient, then just send SIGKILL after whatever delay you feel is reasonable. I think most process managers supports this kind of thing.

**Comment by miluChen** [comment]
If the worker gets into some kind of infinite loop, it won't die. One would assume that if the consumer is killed, the workers will be killed. Yeah, we can send SIGKILL to kill everything, but I guess that should be the last option. And it'll be good if huey provides better options.

**Comment by coleifer** [comment]
Ah, I guess it is behaving differently with processes than when using threads. I just made a test of using TERM with a blocked worker and indeed -- the worker does not shut down immediately. Let me look into it.

**Comment by coleifer** [comment]
Resolved. Essentially, I needed to add the appropriate SIGTERM handler for the child (worker) processes so that they would shutdown.

Here's some sample output running a task that just calls time.sleep() for a given amount of time.

Graceful shutdown - the interrupt is received, but the consumer doesn't exit until the task finishes executing:

```
[2019-10-04 22:35:33,778] INFO:huey:7046:Executing hx.slow: 63c171b5-c249-416d-913f-7eae9a1c71e2
[2019-10-04 22:35:44,232] INFO:huey.consumer:7043:Received SIGINT
[2019-10-04 22:35:44,234] INFO:huey.consumer:7043:Shutting down gracefully...
done sleeping: 20
[2019-10-04 22:35:53,799] INFO:huey:7046:hx.slow: 63c171b5-c249-416d-913f-7eae9a1c71e2 executed in 20.020s
[2019-10-04 22:35:53,801] INFO:huey.consumer:7043:All workers have stopped.
[2019-10-04 22:35:53,802] INFO:huey.consumer:7043:Consumer exiting.
```

Immediate shutdown - the terminate signal is received and any workers actively running a task will stop and indicate the task was not finished:

```
[2019-10-04 22:35:11,947] INFO:huey:6740:Executing hx.slow: 883b3efb-f82a-4d23-b0dd-34a93e4b414f
[2019-10-04 22:35:19,790] INFO:huey.consumer:6737:Received SIGTERM
[2019-10-04 22:35:19,845] INFO:huey.consumer:6737:Shutting down
[2019-10-04 22:35:19,845] INFO:huey.consumer:6737:Consumer exiting.
[2019-10-04 22:35:19,846] WARNING:huey:6740:Received exit signal, 883b3efb-f82a-4d23-b0dd-34a93e4b414f did not finish.
```

**Comment by miluChen** [comment]
👍 One more question.. when we send SIGTERM signal, do we just need to send it to the consumer? And the consumer propagates the signal to the workers?

**Comment by coleifer** [comment]
Just to the consumer.

**Comment by samos123** [comment]
I seem to still have an issue that huey won't shutdown after sending SIGTERM when using greenlets. I have to force kill it with `kill -9 $PID`.

**Comment by coleifer** [comment]
It sounds like a missing monkey-patch to me. You may need to ensure that `from gevent import monkey ; monkey.patch_all()` is being executed at the entry-point of your application.

If you go to the huey examples directory in the source tree you can verify for yourself that the following is well-behaved:

```
$ cd examples/simple
$ WORKER_CLASS=greenlet ./cons.sh greenlet
HUEY CONSUMER
-------------
In another terminal, run 'python main.py'
Stop the consumer using Ctrl+C
Monkey-patching for gevent.
09:11:40 Huey consumer started with 4 greenlet, PID 9350 at 2023-02-28 15:11:40.340802
09:11:40 Scheduler runs every 1 second(s).
09:11:40 Periodic tasks are enabled.
09:11:40 The following commands are available:
+ tasks.add
+ tasks.mul
+ tasks.slow
+ tasks.flaky_task
+ tasks.add_pipeline
+ tasks.every_other_minute
+ tasks.every_five_mins
process 9350, thread 140664396583264 - startup hook
process 9350, thread 140664396583544 - startup hook
process 9350, thread 140664396583824 - startup hook
process 9350, thread 140664396584104 - startup hook
^CKeyboardInterrupt
2023-02-28T15:11:42Z
09:11:42 Received SIGINT
09:11:42 Shutting down gracefully...
process 9350, thread 140664396583264 - shutdown hook
process 9350, thread 140664396583544 - shutdown hook
process 9350, thread 140664396583824 - shutdown hook
process 9350, thread 140664396584104 - shutdown hook
09:11:42 All workers have stopped.
09:11:42 Consumer exiting.
```
